#!/bin/sh
##################
# do_temp - Read the TC74 temperature sensor and write the current temp to
#          "last-known-good" files
#
# HISTORICAL INFORMATION -
#
#  2018-01-22  msipin/epowell  Created
#  2018-05-18  msipin/epowell  Supported command-line I2C address
#################

# All last-known-good data will be written to files in the following directory -
LAST_KNOWN_GOOD_DIR=/usr/local/bin


temp=`readtemp 0x49`
echo $temp > ${LAST_KNOWN_GOOD_DIR}/temp
echo $temp

exit 0

