#!/bin/sh
##################
# do_temp - Read the TC74 temperature sensor and write the current temp to
#          "last-known-good" files
#
# HISTORICAL INFORMATION -
#
#  2018-01-22  msipin/epowell  Created
#  2018-05-18  msipin/epowell  Supported command-line I2C address
#  2018-05-24  msipin  Replaced original (one) temp sensor with two and matched
#                      Eric's sensor addresses. Read from and reported on both
#################

# All last-known-good data will be written to files in the following directory -
LAST_KNOWN_GOOD_DIR=/usr/local/bin


temp1=`readtemp 0x48`
temp2=`readtemp 0x4d`
##echo $temp1 > ${LAST_KNOWN_GOOD_DIR}/temp
echo $temp1,$temp2 > ${LAST_KNOWN_GOOD_DIR}/temp
##echo $temp1
echo $temp1,$temp2

exit 0

