#!/bin/sh

data1="Warpig-II"
data2=`getpos`
data3=`gettemp`
data4=`iwconfig 2>/dev/null | egrep "ESSID:|..:..:..:..:..:.." | grep -v "ESSID:off"`

echo ${data1}
echo ${data2}","${data3}
echo ${data4}

exit 0

