#!/bin/sh

data1=`getpos`
data2=`gettemp`
data3=`iwconfig 2>/dev/null | egrep "ESSID:|..:..:..:..:..:.." | grep -v "ESSID:off"`

echo -n ${data1}
echo -n ","
echo -n ${data2}
echo -n ","
echo ${data3}

exit 0

